run:
  timeout: 5m

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Standard Go analysis (matches your old Makefile)
    - staticcheck   # Industry standard, catches real bugs
    - unused        # Dead code detection

linters-settings:
  govet:
    # Use default checks (same as 'go vet')
    enable-all: false

  errcheck:
    check-blank: true

issues:
  exclude-use-default: false
